### ISSUE TITLE
Mein Computer gibt komische Geräusche von sich

### ISSUE THREAD

**Issue by CoDev21** [bananens0hn/monopoly#3]
Der piept dauernd und raucht. Flammen hab ich aber noch keine gesehen.
![image](https://user-images.githubusercontent.com/44269592/123656218-02af3a00-d830-11eb-9f4e-23d8a1d4b5d6.png)

**Comment by Omega65536** [comment]
Hab das selbe Problem

**Comment by bananens0hn** [comment]
Danke für die hilfreiche Rückmeldung. Wir werden versuchen das Problem in den nächsten drei Jahren zu beheben. Bei weiteren Fragen wenden Sie sich bitte an den Support:
https://www.epicgames.com/help/de/fortnite-c75

**Comment by CoDev21** [comment]
Danke, der Link hat sehr geholfen!
Dieser Kunden-Support ist einzigartig auf der Welt!
